// MK Cars — inventory data
// Using Unsplash car photography (public, free to use)

const CARS = [
  {
    id: 'porsche-911-turbo-s-2022',
    brand: 'Porsche',
    model: '911 Turbo S',
    year: 2022,
    price: 198500,
    mileage: 8200,
    type: 'Coupe',
    transmission: 'PDK',
    fuel: 'Petrol',
    color: 'GT Silver Metallic',
    drivetrain: 'AWD',
    power: 640,
    accel: 2.7,
    topSpeed: 330,
    engine: '3.7L Twin-Turbo Flat-6',
    img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Single-owner 992-generation Turbo S in pristine condition. Sport Chrono package, ceramic brakes, full carbon interior. Comprehensive Porsche service history.",
    featured: true,
    tags: ['Performance', 'Single Owner', 'Ceramic Brakes'],
  },
  {
    id: 'mercedes-amg-gt-2021',
    brand: 'Mercedes',
    model: 'AMG GT 63 S',
    year: 2021,
    price: 142000,
    mileage: 14500,
    type: 'Coupe',
    transmission: 'Automatic',
    fuel: 'Petrol',
    color: 'Obsidian Black',
    drivetrain: 'AWD',
    power: 630,
    accel: 3.1,
    topSpeed: 315,
    engine: '4.0L Twin-Turbo V8',
    img: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Four-door AMG GT 63 S with Edition 1 package. Carbon fiber trim, AMG performance seats, Burmester sound system. Recently serviced by Mercedes-Benz.",
    featured: true,
    tags: ['AMG Performance', 'Edition 1'],
  },
  {
    id: 'bmw-m5-cs-2022',
    brand: 'BMW',
    model: 'M5 CS',
    year: 2022,
    price: 168000,
    mileage: 6100,
    type: 'Sedan',
    transmission: 'Automatic',
    fuel: 'Petrol',
    color: 'Frozen Brands Hatch Grey',
    drivetrain: 'AWD',
    power: 635,
    accel: 3.0,
    topSpeed: 305,
    engine: '4.4L Twin-Turbo V8',
    img: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Limited production M5 CS — the most powerful M5 ever. Carbon bucket seats, gold accents, M Carbon Ceramic brakes. Collector-grade example.",
    featured: false,
    tags: ['Limited Edition', 'Collector'],
  },
  {
    id: 'audi-rs-e-tron-gt-2023',
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2023,
    price: 124900,
    mileage: 9800,
    type: 'Sedan',
    transmission: 'Automatic',
    fuel: 'Electric',
    color: 'Daytona Grey',
    drivetrain: 'AWD',
    power: 637,
    accel: 3.3,
    topSpeed: 250,
    engine: 'Dual Electric Motor',
    img: 'https://images.unsplash.com/photo-1614200179396-2bdb77ebf81b?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "All-electric grand tourer with 93kWh battery and 800V architecture. Matrix LED headlights, panoramic roof, premium Bang & Olufsen audio.",
    featured: false,
    tags: ['Electric', 'Matrix LED'],
  },
  {
    id: 'lamborghini-huracan-evo-2021',
    brand: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2021,
    price: 245000,
    mileage: 4200,
    type: 'Coupe',
    transmission: 'DCT',
    fuel: 'Petrol',
    color: 'Verde Mantis',
    drivetrain: 'AWD',
    power: 631,
    accel: 2.9,
    topSpeed: 325,
    engine: '5.2L Naturally Aspirated V10',
    img: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Naturally aspirated V10 in stunning Verde Mantis. Lifting system, sport exhaust, Alcantara interior. Low-mileage, garage-kept since new.",
    featured: true,
    tags: ['V10', 'Low Mileage'],
  },
  {
    id: 'range-rover-autobiography-2022',
    brand: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2022,
    price: 138500,
    mileage: 18400,
    type: 'SUV',
    transmission: 'Automatic',
    fuel: 'Hybrid',
    color: 'Santorini Black',
    drivetrain: 'AWD',
    power: 523,
    accel: 4.6,
    topSpeed: 250,
    engine: '4.4L Twin-Turbo V8 Mild Hybrid',
    img: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Latest-generation L460 Range Rover with Autobiography spec. Executive rear seats, 23-inch wheels, Meridian Signature audio. One careful owner.",
    featured: false,
    tags: ['Executive', 'One Owner'],
  },
  {
    id: 'aston-martin-db11-2020',
    brand: 'Aston Martin',
    model: 'DB11 V12',
    year: 2020,
    price: 132000,
    mileage: 22100,
    type: 'Coupe',
    transmission: 'Automatic',
    fuel: 'Petrol',
    color: 'Magnetic Silver',
    drivetrain: 'RWD',
    power: 600,
    accel: 3.7,
    topSpeed: 322,
    engine: '5.2L Twin-Turbo V12',
    img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "DB11 in classic Magnetic Silver with full leather interior. Q by Aston Martin specification, premium audio, comprehensive service history.",
    featured: false,
    tags: ['V12', 'Grand Tourer'],
  },
  {
    id: 'tesla-model-s-plaid-2022',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2022,
    price: 89900,
    mileage: 15600,
    type: 'Sedan',
    transmission: 'Automatic',
    fuel: 'Electric',
    color: 'Pearl White',
    drivetrain: 'AWD',
    power: 1020,
    accel: 2.1,
    topSpeed: 322,
    engine: 'Tri-Motor Electric',
    img: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Plaid-spec Model S with 1,020 hp tri-motor setup. Full Self-Driving package included, premium interior, 21-inch arachnid wheels.",
    featured: false,
    tags: ['1020 HP', 'FSD Included'],
  },
  {
    id: 'mclaren-720s-2020',
    brand: 'McLaren',
    model: '720S Performance',
    year: 2020,
    price: 218000,
    mileage: 7800,
    type: 'Coupe',
    transmission: 'DCT',
    fuel: 'Petrol',
    color: 'Aurora Blue',
    drivetrain: 'RWD',
    power: 710,
    accel: 2.8,
    topSpeed: 341,
    engine: '4.0L Twin-Turbo V8',
    img: 'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Performance-spec 720S with carbon fibre exterior pack. Lifter, sports exhaust, MSO interior. Recent McLaren-certified service.",
    featured: false,
    tags: ['Carbon Pack', 'MSO Interior'],
  },
  {
    id: 'bentley-continental-gt-2021',
    brand: 'Bentley',
    model: 'Continental GT V8',
    year: 2021,
    price: 158000,
    mileage: 12300,
    type: 'Coupe',
    transmission: 'Automatic',
    fuel: 'Petrol',
    color: 'Onyx Black',
    drivetrain: 'AWD',
    power: 542,
    accel: 4.0,
    topSpeed: 318,
    engine: '4.0L Twin-Turbo V8',
    img: 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Mulliner-spec Continental GT in Onyx with Linen leather. Naim audio, rotating dashboard, 22-inch black-painted wheels.",
    featured: false,
    tags: ['Mulliner Spec', 'Naim Audio'],
  },
  {
    id: 'ferrari-roma-2021',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2021,
    price: 232000,
    mileage: 5400,
    type: 'Coupe',
    transmission: 'DCT',
    fuel: 'Petrol',
    color: 'Rosso Corsa',
    drivetrain: 'RWD',
    power: 612,
    accel: 3.4,
    topSpeed: 320,
    engine: '3.9L Twin-Turbo V8',
    img: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Ferrari Roma in classic Rosso Corsa. Daytona seats, carbon fibre driver zone, premium JBL sound system. Ferrari Approved program.",
    featured: true,
    tags: ['Ferrari Approved', 'Daytona Seats'],
  },
  {
    id: 'rolls-royce-ghost-2022',
    brand: 'Rolls-Royce',
    model: 'Ghost',
    year: 2022,
    price: 318000,
    mileage: 4800,
    type: 'Sedan',
    transmission: 'Automatic',
    fuel: 'Petrol',
    color: 'Arctic White',
    drivetrain: 'AWD',
    power: 563,
    accel: 4.8,
    topSpeed: 250,
    engine: '6.75L Twin-Turbo V12',
    img: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=1600&q=85&auto=format&fit=crop',
    location: 'MK Showroom · Los Angeles',
    description: "Eighth-generation Ghost with Bespoke specification. Starlight headliner, rear theater configuration, signature umbrellas in doors.",
    featured: false,
    tags: ['Bespoke', 'Starlight Headliner'],
  },
];

const BRANDS = ['All', 'Porsche', 'Mercedes', 'BMW', 'Audi', 'Lamborghini', 'Ferrari', 'McLaren', 'Aston Martin', 'Bentley', 'Rolls-Royce', 'Land Rover', 'Tesla'];
const TYPES = ['All', 'Coupe', 'Sedan', 'SUV'];
const FUELS = ['All', 'Petrol', 'Electric', 'Hybrid'];

const TESTIMONIALS = [
  { name: 'Wade Sterling', role: 'Collector', quote: 'MK Cars sourced an exact-spec 911 GT3 for me in two weeks. The condition exceeded the listing photos.' },
  { name: 'Elena Voss', role: 'Repeat client', quote: 'Third car I have purchased from MK. The handover process is genuinely the best in the industry.' },
];

window.MK_DATA = { CARS, BRANDS, TYPES, FUELS, TESTIMONIALS };
